apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  initContainers:
  - name: check-db
    image: busybox
    command: ['/bin/sh']
    args: ['-c', 'until nc -z db-service 3306; do echo waiting for db-service; sleep 5; done;']
  containers:
  - name: app
    image: harbor.testlab.local/library/webapp
    env:
    - name: DB_HOST
      value: db-service
    - name: DB_PORT
      value: "3306"
